// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/renderinc/stackpath-cdn-go/models"
)

// NewCreateScopeRuleParams creates a new CreateScopeRuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateScopeRuleParams() *CreateScopeRuleParams {
	return &CreateScopeRuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateScopeRuleParamsWithTimeout creates a new CreateScopeRuleParams object
// with the ability to set a timeout on a request.
func NewCreateScopeRuleParamsWithTimeout(timeout time.Duration) *CreateScopeRuleParams {
	return &CreateScopeRuleParams{
		timeout: timeout,
	}
}

// NewCreateScopeRuleParamsWithContext creates a new CreateScopeRuleParams object
// with the ability to set a context for a request.
func NewCreateScopeRuleParamsWithContext(ctx context.Context) *CreateScopeRuleParams {
	return &CreateScopeRuleParams{
		Context: ctx,
	}
}

// NewCreateScopeRuleParamsWithHTTPClient creates a new CreateScopeRuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateScopeRuleParamsWithHTTPClient(client *http.Client) *CreateScopeRuleParams {
	return &CreateScopeRuleParams{
		HTTPClient: client,
	}
}

/* CreateScopeRuleParams contains all the parameters to send to the API endpoint
   for the create scope rule operation.

   Typically these are written to a http.Request.
*/
type CreateScopeRuleParams struct {

	// Body.
	Body *models.CdnCreateScopeRuleRequest

	/* ScopeID.

	   The ID of the CDN site scope to create an EdgeRule on
	*/
	ScopeID string

	/* SiteID.

	   The ID of the site to create an EdgeRule on
	*/
	SiteID string

	/* StackID.

	   The ID of the stack containing the site to create an EdgeRule on
	*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create scope rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateScopeRuleParams) WithDefaults() *CreateScopeRuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create scope rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateScopeRuleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create scope rule params
func (o *CreateScopeRuleParams) WithTimeout(timeout time.Duration) *CreateScopeRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create scope rule params
func (o *CreateScopeRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create scope rule params
func (o *CreateScopeRuleParams) WithContext(ctx context.Context) *CreateScopeRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create scope rule params
func (o *CreateScopeRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create scope rule params
func (o *CreateScopeRuleParams) WithHTTPClient(client *http.Client) *CreateScopeRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create scope rule params
func (o *CreateScopeRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create scope rule params
func (o *CreateScopeRuleParams) WithBody(body *models.CdnCreateScopeRuleRequest) *CreateScopeRuleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create scope rule params
func (o *CreateScopeRuleParams) SetBody(body *models.CdnCreateScopeRuleRequest) {
	o.Body = body
}

// WithScopeID adds the scopeID to the create scope rule params
func (o *CreateScopeRuleParams) WithScopeID(scopeID string) *CreateScopeRuleParams {
	o.SetScopeID(scopeID)
	return o
}

// SetScopeID adds the scopeId to the create scope rule params
func (o *CreateScopeRuleParams) SetScopeID(scopeID string) {
	o.ScopeID = scopeID
}

// WithSiteID adds the siteID to the create scope rule params
func (o *CreateScopeRuleParams) WithSiteID(siteID string) *CreateScopeRuleParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the create scope rule params
func (o *CreateScopeRuleParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithStackID adds the stackID to the create scope rule params
func (o *CreateScopeRuleParams) WithStackID(stackID string) *CreateScopeRuleParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the create scope rule params
func (o *CreateScopeRuleParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateScopeRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param scope_id
	if err := r.SetPathParam("scope_id", o.ScopeID); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
