// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/renderinc/stackpath-cdn-go/models"
)

// DeleteCertificateReader is a Reader for the DeleteCertificate structure.
type DeleteCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteCertificateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteCertificateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteCertificateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDeleteCertificateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteCertificateNoContent creates a DeleteCertificateNoContent with default headers values
func NewDeleteCertificateNoContent() *DeleteCertificateNoContent {
	return &DeleteCertificateNoContent{}
}

/*DeleteCertificateNoContent handles this case with default header values.

No content
*/
type DeleteCertificateNoContent struct {
}

func (o *DeleteCertificateNoContent) Error() string {
	return fmt.Sprintf("[DELETE /cdn/v1/stacks/{stack_id}/certificates/{certificate_id}][%d] deleteCertificateNoContent ", 204)
}

func (o *DeleteCertificateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCertificateUnauthorized creates a DeleteCertificateUnauthorized with default headers values
func NewDeleteCertificateUnauthorized() *DeleteCertificateUnauthorized {
	return &DeleteCertificateUnauthorized{}
}

/*DeleteCertificateUnauthorized handles this case with default header values.

Returned when an unauthorized request is attempted.
*/
type DeleteCertificateUnauthorized struct {
	Payload *models.APIStatus
}

func (o *DeleteCertificateUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /cdn/v1/stacks/{stack_id}/certificates/{certificate_id}][%d] deleteCertificateUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteCertificateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCertificateInternalServerError creates a DeleteCertificateInternalServerError with default headers values
func NewDeleteCertificateInternalServerError() *DeleteCertificateInternalServerError {
	return &DeleteCertificateInternalServerError{}
}

/*DeleteCertificateInternalServerError handles this case with default header values.

Internal server error.
*/
type DeleteCertificateInternalServerError struct {
	Payload *models.APIStatus
}

func (o *DeleteCertificateInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /cdn/v1/stacks/{stack_id}/certificates/{certificate_id}][%d] deleteCertificateInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteCertificateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCertificateDefault creates a DeleteCertificateDefault with default headers values
func NewDeleteCertificateDefault(code int) *DeleteCertificateDefault {
	return &DeleteCertificateDefault{
		_statusCode: code,
	}
}

/*DeleteCertificateDefault handles this case with default header values.

Default error structure.
*/
type DeleteCertificateDefault struct {
	_statusCode int

	Payload *models.APIStatus
}

// Code gets the status code for the delete certificate default response
func (o *DeleteCertificateDefault) Code() int {
	return o._statusCode
}

func (o *DeleteCertificateDefault) Error() string {
	return fmt.Sprintf("[DELETE /cdn/v1/stacks/{stack_id}/certificates/{certificate_id}][%d] DeleteCertificate default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteCertificateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
