// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSiteScriptParams creates a new DeleteSiteScriptParams object
// with the default values initialized.
func NewDeleteSiteScriptParams() *DeleteSiteScriptParams {
	var ()
	return &DeleteSiteScriptParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSiteScriptParamsWithTimeout creates a new DeleteSiteScriptParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSiteScriptParamsWithTimeout(timeout time.Duration) *DeleteSiteScriptParams {
	var ()
	return &DeleteSiteScriptParams{

		timeout: timeout,
	}
}

// NewDeleteSiteScriptParamsWithContext creates a new DeleteSiteScriptParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSiteScriptParamsWithContext(ctx context.Context) *DeleteSiteScriptParams {
	var ()
	return &DeleteSiteScriptParams{

		Context: ctx,
	}
}

// NewDeleteSiteScriptParamsWithHTTPClient creates a new DeleteSiteScriptParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSiteScriptParamsWithHTTPClient(client *http.Client) *DeleteSiteScriptParams {
	var ()
	return &DeleteSiteScriptParams{
		HTTPClient: client,
	}
}

/*DeleteSiteScriptParams contains all the parameters to send to the API endpoint
for the delete site script operation typically these are written to a http.Request
*/
type DeleteSiteScriptParams struct {

	/*ScriptID*/
	ScriptID string
	/*SiteID*/
	SiteID string
	/*StackID*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete site script params
func (o *DeleteSiteScriptParams) WithTimeout(timeout time.Duration) *DeleteSiteScriptParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete site script params
func (o *DeleteSiteScriptParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete site script params
func (o *DeleteSiteScriptParams) WithContext(ctx context.Context) *DeleteSiteScriptParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete site script params
func (o *DeleteSiteScriptParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete site script params
func (o *DeleteSiteScriptParams) WithHTTPClient(client *http.Client) *DeleteSiteScriptParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete site script params
func (o *DeleteSiteScriptParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithScriptID adds the scriptID to the delete site script params
func (o *DeleteSiteScriptParams) WithScriptID(scriptID string) *DeleteSiteScriptParams {
	o.SetScriptID(scriptID)
	return o
}

// SetScriptID adds the scriptId to the delete site script params
func (o *DeleteSiteScriptParams) SetScriptID(scriptID string) {
	o.ScriptID = scriptID
}

// WithSiteID adds the siteID to the delete site script params
func (o *DeleteSiteScriptParams) WithSiteID(siteID string) *DeleteSiteScriptParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the delete site script params
func (o *DeleteSiteScriptParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithStackID adds the stackID to the delete site script params
func (o *DeleteSiteScriptParams) WithStackID(stackID string) *DeleteSiteScriptParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the delete site script params
func (o *DeleteSiteScriptParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSiteScriptParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param script_id
	if err := r.SetPathParam("script_id", o.ScriptID); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
