// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDisableSiteParams creates a new DisableSiteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDisableSiteParams() *DisableSiteParams {
	return &DisableSiteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDisableSiteParamsWithTimeout creates a new DisableSiteParams object
// with the ability to set a timeout on a request.
func NewDisableSiteParamsWithTimeout(timeout time.Duration) *DisableSiteParams {
	return &DisableSiteParams{
		timeout: timeout,
	}
}

// NewDisableSiteParamsWithContext creates a new DisableSiteParams object
// with the ability to set a context for a request.
func NewDisableSiteParamsWithContext(ctx context.Context) *DisableSiteParams {
	return &DisableSiteParams{
		Context: ctx,
	}
}

// NewDisableSiteParamsWithHTTPClient creates a new DisableSiteParams object
// with the ability to set a custom HTTPClient for a request.
func NewDisableSiteParamsWithHTTPClient(client *http.Client) *DisableSiteParams {
	return &DisableSiteParams{
		HTTPClient: client,
	}
}

/* DisableSiteParams contains all the parameters to send to the API endpoint
   for the disable site operation.

   Typically these are written to a http.Request.
*/
type DisableSiteParams struct {

	/* SiteID.

	   The ID of the site to disable
	*/
	SiteID string

	/* StackID.

	   The ID of the stack containing the site to disable
	*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the disable site params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DisableSiteParams) WithDefaults() *DisableSiteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the disable site params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DisableSiteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the disable site params
func (o *DisableSiteParams) WithTimeout(timeout time.Duration) *DisableSiteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the disable site params
func (o *DisableSiteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the disable site params
func (o *DisableSiteParams) WithContext(ctx context.Context) *DisableSiteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the disable site params
func (o *DisableSiteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the disable site params
func (o *DisableSiteParams) WithHTTPClient(client *http.Client) *DisableSiteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the disable site params
func (o *DisableSiteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSiteID adds the siteID to the disable site params
func (o *DisableSiteParams) WithSiteID(siteID string) *DisableSiteParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the disable site params
func (o *DisableSiteParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithStackID adds the stackID to the disable site params
func (o *DisableSiteParams) WithStackID(stackID string) *DisableSiteParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the disable site params
func (o *DisableSiteParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *DisableSiteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
