// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/renderinc/stackpath-cdn-go/models"
)

// DisableSiteReader is a Reader for the DisableSite structure.
type DisableSiteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DisableSiteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDisableSiteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDisableSiteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDisableSiteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDisableSiteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDisableSiteNoContent creates a DisableSiteNoContent with default headers values
func NewDisableSiteNoContent() *DisableSiteNoContent {
	return &DisableSiteNoContent{}
}

/* DisableSiteNoContent describes a response with status code 204, with default header values.

No content
*/
type DisableSiteNoContent struct {
}

func (o *DisableSiteNoContent) Error() string {
	return fmt.Sprintf("[POST /cdn/v1/stacks/{stack_id}/sites/{site_id}/disable][%d] disableSiteNoContent ", 204)
}

func (o *DisableSiteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDisableSiteUnauthorized creates a DisableSiteUnauthorized with default headers values
func NewDisableSiteUnauthorized() *DisableSiteUnauthorized {
	return &DisableSiteUnauthorized{}
}

/* DisableSiteUnauthorized describes a response with status code 401, with default header values.

Returned when an unauthorized request is attempted.
*/
type DisableSiteUnauthorized struct {
	Payload *models.APIStatus
}

func (o *DisableSiteUnauthorized) Error() string {
	return fmt.Sprintf("[POST /cdn/v1/stacks/{stack_id}/sites/{site_id}/disable][%d] disableSiteUnauthorized  %+v", 401, o.Payload)
}
func (o *DisableSiteUnauthorized) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *DisableSiteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisableSiteInternalServerError creates a DisableSiteInternalServerError with default headers values
func NewDisableSiteInternalServerError() *DisableSiteInternalServerError {
	return &DisableSiteInternalServerError{}
}

/* DisableSiteInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DisableSiteInternalServerError struct {
	Payload *models.APIStatus
}

func (o *DisableSiteInternalServerError) Error() string {
	return fmt.Sprintf("[POST /cdn/v1/stacks/{stack_id}/sites/{site_id}/disable][%d] disableSiteInternalServerError  %+v", 500, o.Payload)
}
func (o *DisableSiteInternalServerError) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *DisableSiteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisableSiteDefault creates a DisableSiteDefault with default headers values
func NewDisableSiteDefault(code int) *DisableSiteDefault {
	return &DisableSiteDefault{
		_statusCode: code,
	}
}

/* DisableSiteDefault describes a response with status code -1, with default header values.

Default error structure.
*/
type DisableSiteDefault struct {
	_statusCode int

	Payload *models.APIStatus
}

// Code gets the status code for the disable site default response
func (o *DisableSiteDefault) Code() int {
	return o._statusCode
}

func (o *DisableSiteDefault) Error() string {
	return fmt.Sprintf("[POST /cdn/v1/stacks/{stack_id}/sites/{site_id}/disable][%d] DisableSite default  %+v", o._statusCode, o.Payload)
}
func (o *DisableSiteDefault) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *DisableSiteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
