// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetScopeConfigurationParams creates a new GetScopeConfigurationParams object
// with the default values initialized.
func NewGetScopeConfigurationParams() *GetScopeConfigurationParams {
	var ()
	return &GetScopeConfigurationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScopeConfigurationParamsWithTimeout creates a new GetScopeConfigurationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScopeConfigurationParamsWithTimeout(timeout time.Duration) *GetScopeConfigurationParams {
	var ()
	return &GetScopeConfigurationParams{

		timeout: timeout,
	}
}

// NewGetScopeConfigurationParamsWithContext creates a new GetScopeConfigurationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScopeConfigurationParamsWithContext(ctx context.Context) *GetScopeConfigurationParams {
	var ()
	return &GetScopeConfigurationParams{

		Context: ctx,
	}
}

// NewGetScopeConfigurationParamsWithHTTPClient creates a new GetScopeConfigurationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScopeConfigurationParamsWithHTTPClient(client *http.Client) *GetScopeConfigurationParams {
	var ()
	return &GetScopeConfigurationParams{
		HTTPClient: client,
	}
}

/*GetScopeConfigurationParams contains all the parameters to send to the API endpoint
for the get scope configuration operation typically these are written to a http.Request
*/
type GetScopeConfigurationParams struct {

	/*ScopeID*/
	ScopeID string
	/*SiteID*/
	SiteID string
	/*StackID*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get scope configuration params
func (o *GetScopeConfigurationParams) WithTimeout(timeout time.Duration) *GetScopeConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scope configuration params
func (o *GetScopeConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scope configuration params
func (o *GetScopeConfigurationParams) WithContext(ctx context.Context) *GetScopeConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scope configuration params
func (o *GetScopeConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scope configuration params
func (o *GetScopeConfigurationParams) WithHTTPClient(client *http.Client) *GetScopeConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scope configuration params
func (o *GetScopeConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithScopeID adds the scopeID to the get scope configuration params
func (o *GetScopeConfigurationParams) WithScopeID(scopeID string) *GetScopeConfigurationParams {
	o.SetScopeID(scopeID)
	return o
}

// SetScopeID adds the scopeId to the get scope configuration params
func (o *GetScopeConfigurationParams) SetScopeID(scopeID string) {
	o.ScopeID = scopeID
}

// WithSiteID adds the siteID to the get scope configuration params
func (o *GetScopeConfigurationParams) WithSiteID(siteID string) *GetScopeConfigurationParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the get scope configuration params
func (o *GetScopeConfigurationParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithStackID adds the stackID to the get scope configuration params
func (o *GetScopeConfigurationParams) WithStackID(stackID string) *GetScopeConfigurationParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get scope configuration params
func (o *GetScopeConfigurationParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *GetScopeConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param scope_id
	if err := r.SetPathParam("scope_id", o.ScopeID); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
