// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/renderinc/stackpath-cdn-go/models"
)

// GetSiteCertificatesReader is a Reader for the GetSiteCertificates structure.
type GetSiteCertificatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSiteCertificatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSiteCertificatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetSiteCertificatesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSiteCertificatesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetSiteCertificatesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSiteCertificatesOK creates a GetSiteCertificatesOK with default headers values
func NewGetSiteCertificatesOK() *GetSiteCertificatesOK {
	return &GetSiteCertificatesOK{}
}

/* GetSiteCertificatesOK describes a response with status code 200, with default header values.

GetSiteCertificatesOK get site certificates o k
*/
type GetSiteCertificatesOK struct {
	Payload *models.CdnGetSiteCertificatesResponse
}

func (o *GetSiteCertificatesOK) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/sites/{site_id}/certificates][%d] getSiteCertificatesOK  %+v", 200, o.Payload)
}
func (o *GetSiteCertificatesOK) GetPayload() *models.CdnGetSiteCertificatesResponse {
	return o.Payload
}

func (o *GetSiteCertificatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CdnGetSiteCertificatesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSiteCertificatesUnauthorized creates a GetSiteCertificatesUnauthorized with default headers values
func NewGetSiteCertificatesUnauthorized() *GetSiteCertificatesUnauthorized {
	return &GetSiteCertificatesUnauthorized{}
}

/* GetSiteCertificatesUnauthorized describes a response with status code 401, with default header values.

Returned when an unauthorized request is attempted.
*/
type GetSiteCertificatesUnauthorized struct {
	Payload *models.APIStatus
}

func (o *GetSiteCertificatesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/sites/{site_id}/certificates][%d] getSiteCertificatesUnauthorized  %+v", 401, o.Payload)
}
func (o *GetSiteCertificatesUnauthorized) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *GetSiteCertificatesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSiteCertificatesInternalServerError creates a GetSiteCertificatesInternalServerError with default headers values
func NewGetSiteCertificatesInternalServerError() *GetSiteCertificatesInternalServerError {
	return &GetSiteCertificatesInternalServerError{}
}

/* GetSiteCertificatesInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetSiteCertificatesInternalServerError struct {
	Payload *models.APIStatus
}

func (o *GetSiteCertificatesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/sites/{site_id}/certificates][%d] getSiteCertificatesInternalServerError  %+v", 500, o.Payload)
}
func (o *GetSiteCertificatesInternalServerError) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *GetSiteCertificatesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSiteCertificatesDefault creates a GetSiteCertificatesDefault with default headers values
func NewGetSiteCertificatesDefault(code int) *GetSiteCertificatesDefault {
	return &GetSiteCertificatesDefault{
		_statusCode: code,
	}
}

/* GetSiteCertificatesDefault describes a response with status code -1, with default header values.

Default error structure.
*/
type GetSiteCertificatesDefault struct {
	_statusCode int

	Payload *models.APIStatus
}

// Code gets the status code for the get site certificates default response
func (o *GetSiteCertificatesDefault) Code() int {
	return o._statusCode
}

func (o *GetSiteCertificatesDefault) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/sites/{site_id}/certificates][%d] GetSiteCertificates default  %+v", o._statusCode, o.Payload)
}
func (o *GetSiteCertificatesDefault) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *GetSiteCertificatesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
