// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOriginsParams creates a new GetOriginsParams object
// with the default values initialized.
func NewGetOriginsParams() *GetOriginsParams {
	var ()
	return &GetOriginsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOriginsParamsWithTimeout creates a new GetOriginsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOriginsParamsWithTimeout(timeout time.Duration) *GetOriginsParams {
	var ()
	return &GetOriginsParams{

		timeout: timeout,
	}
}

// NewGetOriginsParamsWithContext creates a new GetOriginsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOriginsParamsWithContext(ctx context.Context) *GetOriginsParams {
	var ()
	return &GetOriginsParams{

		Context: ctx,
	}
}

// NewGetOriginsParamsWithHTTPClient creates a new GetOriginsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOriginsParamsWithHTTPClient(client *http.Client) *GetOriginsParams {
	var ()
	return &GetOriginsParams{
		HTTPClient: client,
	}
}

/*GetOriginsParams contains all the parameters to send to the API endpoint
for the get origins operation typically these are written to a http.Request
*/
type GetOriginsParams struct {

	/*PageRequestAfter
	  The cursor value after which data will be returned.

	*/
	PageRequestAfter *string
	/*PageRequestFilter
	  SQL-style constraint filters.

	*/
	PageRequestFilter *string
	/*PageRequestFirst
	  The number of items desired.

	*/
	PageRequestFirst *string
	/*PageRequestSortBy
	  Sort the response by the given field.

	*/
	PageRequestSortBy *string
	/*StackID
	  The ID of the stack to retrieve origins from

	*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get origins params
func (o *GetOriginsParams) WithTimeout(timeout time.Duration) *GetOriginsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get origins params
func (o *GetOriginsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get origins params
func (o *GetOriginsParams) WithContext(ctx context.Context) *GetOriginsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get origins params
func (o *GetOriginsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get origins params
func (o *GetOriginsParams) WithHTTPClient(client *http.Client) *GetOriginsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get origins params
func (o *GetOriginsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPageRequestAfter adds the pageRequestAfter to the get origins params
func (o *GetOriginsParams) WithPageRequestAfter(pageRequestAfter *string) *GetOriginsParams {
	o.SetPageRequestAfter(pageRequestAfter)
	return o
}

// SetPageRequestAfter adds the pageRequestAfter to the get origins params
func (o *GetOriginsParams) SetPageRequestAfter(pageRequestAfter *string) {
	o.PageRequestAfter = pageRequestAfter
}

// WithPageRequestFilter adds the pageRequestFilter to the get origins params
func (o *GetOriginsParams) WithPageRequestFilter(pageRequestFilter *string) *GetOriginsParams {
	o.SetPageRequestFilter(pageRequestFilter)
	return o
}

// SetPageRequestFilter adds the pageRequestFilter to the get origins params
func (o *GetOriginsParams) SetPageRequestFilter(pageRequestFilter *string) {
	o.PageRequestFilter = pageRequestFilter
}

// WithPageRequestFirst adds the pageRequestFirst to the get origins params
func (o *GetOriginsParams) WithPageRequestFirst(pageRequestFirst *string) *GetOriginsParams {
	o.SetPageRequestFirst(pageRequestFirst)
	return o
}

// SetPageRequestFirst adds the pageRequestFirst to the get origins params
func (o *GetOriginsParams) SetPageRequestFirst(pageRequestFirst *string) {
	o.PageRequestFirst = pageRequestFirst
}

// WithPageRequestSortBy adds the pageRequestSortBy to the get origins params
func (o *GetOriginsParams) WithPageRequestSortBy(pageRequestSortBy *string) *GetOriginsParams {
	o.SetPageRequestSortBy(pageRequestSortBy)
	return o
}

// SetPageRequestSortBy adds the pageRequestSortBy to the get origins params
func (o *GetOriginsParams) SetPageRequestSortBy(pageRequestSortBy *string) {
	o.PageRequestSortBy = pageRequestSortBy
}

// WithStackID adds the stackID to the get origins params
func (o *GetOriginsParams) WithStackID(stackID string) *GetOriginsParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get origins params
func (o *GetOriginsParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOriginsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PageRequestAfter != nil {

		// query param page_request.after
		var qrPageRequestAfter string
		if o.PageRequestAfter != nil {
			qrPageRequestAfter = *o.PageRequestAfter
		}
		qPageRequestAfter := qrPageRequestAfter
		if qPageRequestAfter != "" {
			if err := r.SetQueryParam("page_request.after", qPageRequestAfter); err != nil {
				return err
			}
		}

	}

	if o.PageRequestFilter != nil {

		// query param page_request.filter
		var qrPageRequestFilter string
		if o.PageRequestFilter != nil {
			qrPageRequestFilter = *o.PageRequestFilter
		}
		qPageRequestFilter := qrPageRequestFilter
		if qPageRequestFilter != "" {
			if err := r.SetQueryParam("page_request.filter", qPageRequestFilter); err != nil {
				return err
			}
		}

	}

	if o.PageRequestFirst != nil {

		// query param page_request.first
		var qrPageRequestFirst string
		if o.PageRequestFirst != nil {
			qrPageRequestFirst = *o.PageRequestFirst
		}
		qPageRequestFirst := qrPageRequestFirst
		if qPageRequestFirst != "" {
			if err := r.SetQueryParam("page_request.first", qPageRequestFirst); err != nil {
				return err
			}
		}

	}

	if o.PageRequestSortBy != nil {

		// query param page_request.sort_by
		var qrPageRequestSortBy string
		if o.PageRequestSortBy != nil {
			qrPageRequestSortBy = *o.PageRequestSortBy
		}
		qPageRequestSortBy := qrPageRequestSortBy
		if qPageRequestSortBy != "" {
			if err := r.SetQueryParam("page_request.sort_by", qPageRequestSortBy); err != nil {
				return err
			}
		}

	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
