// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScopeRuleParams creates a new GetScopeRuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetScopeRuleParams() *GetScopeRuleParams {
	return &GetScopeRuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetScopeRuleParamsWithTimeout creates a new GetScopeRuleParams object
// with the ability to set a timeout on a request.
func NewGetScopeRuleParamsWithTimeout(timeout time.Duration) *GetScopeRuleParams {
	return &GetScopeRuleParams{
		timeout: timeout,
	}
}

// NewGetScopeRuleParamsWithContext creates a new GetScopeRuleParams object
// with the ability to set a context for a request.
func NewGetScopeRuleParamsWithContext(ctx context.Context) *GetScopeRuleParams {
	return &GetScopeRuleParams{
		Context: ctx,
	}
}

// NewGetScopeRuleParamsWithHTTPClient creates a new GetScopeRuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetScopeRuleParamsWithHTTPClient(client *http.Client) *GetScopeRuleParams {
	return &GetScopeRuleParams{
		HTTPClient: client,
	}
}

/* GetScopeRuleParams contains all the parameters to send to the API endpoint
   for the get scope rule operation.

   Typically these are written to a http.Request.
*/
type GetScopeRuleParams struct {

	/* RuleID.

	   The ID of the EdgeRule to retrieve
	*/
	RuleID string

	/* ScopeID.

	   The ID of the CDN site scope to retrieve an EdgeRule from
	*/
	ScopeID string

	/* SiteID.

	   The ID of the site to retrieve an EdgeRule from
	*/
	SiteID string

	/* StackID.

	   The ID of the stack containing the site to retrieve an EdgeRule from
	*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get scope rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetScopeRuleParams) WithDefaults() *GetScopeRuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get scope rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetScopeRuleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get scope rule params
func (o *GetScopeRuleParams) WithTimeout(timeout time.Duration) *GetScopeRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scope rule params
func (o *GetScopeRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scope rule params
func (o *GetScopeRuleParams) WithContext(ctx context.Context) *GetScopeRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scope rule params
func (o *GetScopeRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scope rule params
func (o *GetScopeRuleParams) WithHTTPClient(client *http.Client) *GetScopeRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scope rule params
func (o *GetScopeRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRuleID adds the ruleID to the get scope rule params
func (o *GetScopeRuleParams) WithRuleID(ruleID string) *GetScopeRuleParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the get scope rule params
func (o *GetScopeRuleParams) SetRuleID(ruleID string) {
	o.RuleID = ruleID
}

// WithScopeID adds the scopeID to the get scope rule params
func (o *GetScopeRuleParams) WithScopeID(scopeID string) *GetScopeRuleParams {
	o.SetScopeID(scopeID)
	return o
}

// SetScopeID adds the scopeId to the get scope rule params
func (o *GetScopeRuleParams) SetScopeID(scopeID string) {
	o.ScopeID = scopeID
}

// WithSiteID adds the siteID to the get scope rule params
func (o *GetScopeRuleParams) WithSiteID(siteID string) *GetScopeRuleParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the get scope rule params
func (o *GetScopeRuleParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithStackID adds the stackID to the get scope rule params
func (o *GetScopeRuleParams) WithStackID(stackID string) *GetScopeRuleParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get scope rule params
func (o *GetScopeRuleParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *GetScopeRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rule_id
	if err := r.SetPathParam("rule_id", o.RuleID); err != nil {
		return err
	}

	// path param scope_id
	if err := r.SetPathParam("scope_id", o.ScopeID); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
