// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetScopeHostnamesParams creates a new GetScopeHostnamesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetScopeHostnamesParams() *GetScopeHostnamesParams {
	return &GetScopeHostnamesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetScopeHostnamesParamsWithTimeout creates a new GetScopeHostnamesParams object
// with the ability to set a timeout on a request.
func NewGetScopeHostnamesParamsWithTimeout(timeout time.Duration) *GetScopeHostnamesParams {
	return &GetScopeHostnamesParams{
		timeout: timeout,
	}
}

// NewGetScopeHostnamesParamsWithContext creates a new GetScopeHostnamesParams object
// with the ability to set a context for a request.
func NewGetScopeHostnamesParamsWithContext(ctx context.Context) *GetScopeHostnamesParams {
	return &GetScopeHostnamesParams{
		Context: ctx,
	}
}

// NewGetScopeHostnamesParamsWithHTTPClient creates a new GetScopeHostnamesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetScopeHostnamesParamsWithHTTPClient(client *http.Client) *GetScopeHostnamesParams {
	return &GetScopeHostnamesParams{
		HTTPClient: client,
	}
}

/* GetScopeHostnamesParams contains all the parameters to send to the API endpoint
   for the get scope hostnames operation.

   Typically these are written to a http.Request.
*/
type GetScopeHostnamesParams struct {

	/* DisableTransparentMode.

	   Whether or not to load hostnames from a CDN site's CDN scope or its WAF scope. When true, this call loads scope hostnames from a CDN site's scope instead of loading from a CDN site's WAF scope, if the site has WAF service.

	   Format: boolean
	*/
	DisableTransparentMode *bool

	/* PageRequestAfter.

	   The cursor value after which data will be returned.
	*/
	PageRequestAfter *string

	/* PageRequestFilter.

	   SQL-style constraint filters.
	*/
	PageRequestFilter *string

	/* PageRequestFirst.

	   The number of items desired.
	*/
	PageRequestFirst *string

	/* PageRequestSortBy.

	   Sort the response by the given field.
	*/
	PageRequestSortBy *string

	/* ScopeID.

	   The ID of the scope to retrieve hostnames from
	*/
	ScopeID string

	/* SiteID.

	   The ID of the site containing the scope to retrieve hostnames from
	*/
	SiteID string

	/* StackID.

	   The ID of the stack containing the site containing the scope to retrieve hostnames from
	*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get scope hostnames params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetScopeHostnamesParams) WithDefaults() *GetScopeHostnamesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get scope hostnames params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetScopeHostnamesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get scope hostnames params
func (o *GetScopeHostnamesParams) WithTimeout(timeout time.Duration) *GetScopeHostnamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scope hostnames params
func (o *GetScopeHostnamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scope hostnames params
func (o *GetScopeHostnamesParams) WithContext(ctx context.Context) *GetScopeHostnamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scope hostnames params
func (o *GetScopeHostnamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scope hostnames params
func (o *GetScopeHostnamesParams) WithHTTPClient(client *http.Client) *GetScopeHostnamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scope hostnames params
func (o *GetScopeHostnamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDisableTransparentMode adds the disableTransparentMode to the get scope hostnames params
func (o *GetScopeHostnamesParams) WithDisableTransparentMode(disableTransparentMode *bool) *GetScopeHostnamesParams {
	o.SetDisableTransparentMode(disableTransparentMode)
	return o
}

// SetDisableTransparentMode adds the disableTransparentMode to the get scope hostnames params
func (o *GetScopeHostnamesParams) SetDisableTransparentMode(disableTransparentMode *bool) {
	o.DisableTransparentMode = disableTransparentMode
}

// WithPageRequestAfter adds the pageRequestAfter to the get scope hostnames params
func (o *GetScopeHostnamesParams) WithPageRequestAfter(pageRequestAfter *string) *GetScopeHostnamesParams {
	o.SetPageRequestAfter(pageRequestAfter)
	return o
}

// SetPageRequestAfter adds the pageRequestAfter to the get scope hostnames params
func (o *GetScopeHostnamesParams) SetPageRequestAfter(pageRequestAfter *string) {
	o.PageRequestAfter = pageRequestAfter
}

// WithPageRequestFilter adds the pageRequestFilter to the get scope hostnames params
func (o *GetScopeHostnamesParams) WithPageRequestFilter(pageRequestFilter *string) *GetScopeHostnamesParams {
	o.SetPageRequestFilter(pageRequestFilter)
	return o
}

// SetPageRequestFilter adds the pageRequestFilter to the get scope hostnames params
func (o *GetScopeHostnamesParams) SetPageRequestFilter(pageRequestFilter *string) {
	o.PageRequestFilter = pageRequestFilter
}

// WithPageRequestFirst adds the pageRequestFirst to the get scope hostnames params
func (o *GetScopeHostnamesParams) WithPageRequestFirst(pageRequestFirst *string) *GetScopeHostnamesParams {
	o.SetPageRequestFirst(pageRequestFirst)
	return o
}

// SetPageRequestFirst adds the pageRequestFirst to the get scope hostnames params
func (o *GetScopeHostnamesParams) SetPageRequestFirst(pageRequestFirst *string) {
	o.PageRequestFirst = pageRequestFirst
}

// WithPageRequestSortBy adds the pageRequestSortBy to the get scope hostnames params
func (o *GetScopeHostnamesParams) WithPageRequestSortBy(pageRequestSortBy *string) *GetScopeHostnamesParams {
	o.SetPageRequestSortBy(pageRequestSortBy)
	return o
}

// SetPageRequestSortBy adds the pageRequestSortBy to the get scope hostnames params
func (o *GetScopeHostnamesParams) SetPageRequestSortBy(pageRequestSortBy *string) {
	o.PageRequestSortBy = pageRequestSortBy
}

// WithScopeID adds the scopeID to the get scope hostnames params
func (o *GetScopeHostnamesParams) WithScopeID(scopeID string) *GetScopeHostnamesParams {
	o.SetScopeID(scopeID)
	return o
}

// SetScopeID adds the scopeId to the get scope hostnames params
func (o *GetScopeHostnamesParams) SetScopeID(scopeID string) {
	o.ScopeID = scopeID
}

// WithSiteID adds the siteID to the get scope hostnames params
func (o *GetScopeHostnamesParams) WithSiteID(siteID string) *GetScopeHostnamesParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the get scope hostnames params
func (o *GetScopeHostnamesParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithStackID adds the stackID to the get scope hostnames params
func (o *GetScopeHostnamesParams) WithStackID(stackID string) *GetScopeHostnamesParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get scope hostnames params
func (o *GetScopeHostnamesParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *GetScopeHostnamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DisableTransparentMode != nil {

		// query param disable_transparent_mode
		var qrDisableTransparentMode bool

		if o.DisableTransparentMode != nil {
			qrDisableTransparentMode = *o.DisableTransparentMode
		}
		qDisableTransparentMode := swag.FormatBool(qrDisableTransparentMode)
		if qDisableTransparentMode != "" {

			if err := r.SetQueryParam("disable_transparent_mode", qDisableTransparentMode); err != nil {
				return err
			}
		}
	}

	if o.PageRequestAfter != nil {

		// query param page_request.after
		var qrPageRequestAfter string

		if o.PageRequestAfter != nil {
			qrPageRequestAfter = *o.PageRequestAfter
		}
		qPageRequestAfter := qrPageRequestAfter
		if qPageRequestAfter != "" {

			if err := r.SetQueryParam("page_request.after", qPageRequestAfter); err != nil {
				return err
			}
		}
	}

	if o.PageRequestFilter != nil {

		// query param page_request.filter
		var qrPageRequestFilter string

		if o.PageRequestFilter != nil {
			qrPageRequestFilter = *o.PageRequestFilter
		}
		qPageRequestFilter := qrPageRequestFilter
		if qPageRequestFilter != "" {

			if err := r.SetQueryParam("page_request.filter", qPageRequestFilter); err != nil {
				return err
			}
		}
	}

	if o.PageRequestFirst != nil {

		// query param page_request.first
		var qrPageRequestFirst string

		if o.PageRequestFirst != nil {
			qrPageRequestFirst = *o.PageRequestFirst
		}
		qPageRequestFirst := qrPageRequestFirst
		if qPageRequestFirst != "" {

			if err := r.SetQueryParam("page_request.first", qPageRequestFirst); err != nil {
				return err
			}
		}
	}

	if o.PageRequestSortBy != nil {

		// query param page_request.sort_by
		var qrPageRequestSortBy string

		if o.PageRequestSortBy != nil {
			qrPageRequestSortBy = *o.PageRequestSortBy
		}
		qPageRequestSortBy := qrPageRequestSortBy
		if qPageRequestSortBy != "" {

			if err := r.SetQueryParam("page_request.sort_by", qPageRequestSortBy); err != nil {
				return err
			}
		}
	}

	// path param scope_id
	if err := r.SetPathParam("scope_id", o.ScopeID); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
