// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/renderinc/stackpath-cdn-go/models"
)

// GetPurgeStatusReader is a Reader for the GetPurgeStatus structure.
type GetPurgeStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPurgeStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPurgeStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetPurgeStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetPurgeStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetPurgeStatusDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPurgeStatusOK creates a GetPurgeStatusOK with default headers values
func NewGetPurgeStatusOK() *GetPurgeStatusOK {
	return &GetPurgeStatusOK{}
}

/*GetPurgeStatusOK handles this case with default header values.

GetPurgeStatusOK get purge status o k
*/
type GetPurgeStatusOK struct {
	Payload *models.CdnGetPurgeStatusResponse
}

func (o *GetPurgeStatusOK) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/purge/{purge_id}][%d] getPurgeStatusOK  %+v", 200, o.Payload)
}

func (o *GetPurgeStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CdnGetPurgeStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPurgeStatusUnauthorized creates a GetPurgeStatusUnauthorized with default headers values
func NewGetPurgeStatusUnauthorized() *GetPurgeStatusUnauthorized {
	return &GetPurgeStatusUnauthorized{}
}

/*GetPurgeStatusUnauthorized handles this case with default header values.

Returned when an unauthorized request is attempted.
*/
type GetPurgeStatusUnauthorized struct {
	Payload *models.APIStatus
}

func (o *GetPurgeStatusUnauthorized) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/purge/{purge_id}][%d] getPurgeStatusUnauthorized  %+v", 401, o.Payload)
}

func (o *GetPurgeStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPurgeStatusInternalServerError creates a GetPurgeStatusInternalServerError with default headers values
func NewGetPurgeStatusInternalServerError() *GetPurgeStatusInternalServerError {
	return &GetPurgeStatusInternalServerError{}
}

/*GetPurgeStatusInternalServerError handles this case with default header values.

Internal server error.
*/
type GetPurgeStatusInternalServerError struct {
	Payload *models.APIStatus
}

func (o *GetPurgeStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/purge/{purge_id}][%d] getPurgeStatusInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPurgeStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPurgeStatusDefault creates a GetPurgeStatusDefault with default headers values
func NewGetPurgeStatusDefault(code int) *GetPurgeStatusDefault {
	return &GetPurgeStatusDefault{
		_statusCode: code,
	}
}

/*GetPurgeStatusDefault handles this case with default header values.

Default error structure.
*/
type GetPurgeStatusDefault struct {
	_statusCode int

	Payload *models.APIStatus
}

// Code gets the status code for the get purge status default response
func (o *GetPurgeStatusDefault) Code() int {
	return o._statusCode
}

func (o *GetPurgeStatusDefault) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/purge/{purge_id}][%d] GetPurgeStatus default  %+v", o._statusCode, o.Payload)
}

func (o *GetPurgeStatusDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
