// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCertificateParams creates a new GetCertificateParams object
// with the default values initialized.
func NewGetCertificateParams() *GetCertificateParams {
	var ()
	return &GetCertificateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCertificateParamsWithTimeout creates a new GetCertificateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCertificateParamsWithTimeout(timeout time.Duration) *GetCertificateParams {
	var ()
	return &GetCertificateParams{

		timeout: timeout,
	}
}

// NewGetCertificateParamsWithContext creates a new GetCertificateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCertificateParamsWithContext(ctx context.Context) *GetCertificateParams {
	var ()
	return &GetCertificateParams{

		Context: ctx,
	}
}

// NewGetCertificateParamsWithHTTPClient creates a new GetCertificateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCertificateParamsWithHTTPClient(client *http.Client) *GetCertificateParams {
	var ()
	return &GetCertificateParams{
		HTTPClient: client,
	}
}

/*GetCertificateParams contains all the parameters to send to the API endpoint
for the get certificate operation typically these are written to a http.Request
*/
type GetCertificateParams struct {

	/*CertificateID*/
	CertificateID string
	/*StackID*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get certificate params
func (o *GetCertificateParams) WithTimeout(timeout time.Duration) *GetCertificateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get certificate params
func (o *GetCertificateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get certificate params
func (o *GetCertificateParams) WithContext(ctx context.Context) *GetCertificateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get certificate params
func (o *GetCertificateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get certificate params
func (o *GetCertificateParams) WithHTTPClient(client *http.Client) *GetCertificateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get certificate params
func (o *GetCertificateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCertificateID adds the certificateID to the get certificate params
func (o *GetCertificateParams) WithCertificateID(certificateID string) *GetCertificateParams {
	o.SetCertificateID(certificateID)
	return o
}

// SetCertificateID adds the certificateId to the get certificate params
func (o *GetCertificateParams) SetCertificateID(certificateID string) {
	o.CertificateID = certificateID
}

// WithStackID adds the stackID to the get certificate params
func (o *GetCertificateParams) WithStackID(stackID string) *GetCertificateParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get certificate params
func (o *GetCertificateParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCertificateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param certificate_id
	if err := r.SetPathParam("certificate_id", o.CertificateID); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
