// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetClosestPopsParams creates a new GetClosestPopsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClosestPopsParams() *GetClosestPopsParams {
	return &GetClosestPopsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClosestPopsParamsWithTimeout creates a new GetClosestPopsParams object
// with the ability to set a timeout on a request.
func NewGetClosestPopsParamsWithTimeout(timeout time.Duration) *GetClosestPopsParams {
	return &GetClosestPopsParams{
		timeout: timeout,
	}
}

// NewGetClosestPopsParamsWithContext creates a new GetClosestPopsParams object
// with the ability to set a context for a request.
func NewGetClosestPopsParamsWithContext(ctx context.Context) *GetClosestPopsParams {
	return &GetClosestPopsParams{
		Context: ctx,
	}
}

// NewGetClosestPopsParamsWithHTTPClient creates a new GetClosestPopsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClosestPopsParamsWithHTTPClient(client *http.Client) *GetClosestPopsParams {
	return &GetClosestPopsParams{
		HTTPClient: client,
	}
}

/* GetClosestPopsParams contains all the parameters to send to the API endpoint
   for the get closest pops operation.

   Typically these are written to a http.Request.
*/
type GetClosestPopsParams struct {

	/* URL.

	   The URL to scan.
	*/
	URL *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get closest pops params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClosestPopsParams) WithDefaults() *GetClosestPopsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get closest pops params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClosestPopsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get closest pops params
func (o *GetClosestPopsParams) WithTimeout(timeout time.Duration) *GetClosestPopsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get closest pops params
func (o *GetClosestPopsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get closest pops params
func (o *GetClosestPopsParams) WithContext(ctx context.Context) *GetClosestPopsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get closest pops params
func (o *GetClosestPopsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get closest pops params
func (o *GetClosestPopsParams) WithHTTPClient(client *http.Client) *GetClosestPopsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get closest pops params
func (o *GetClosestPopsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithURL adds the url to the get closest pops params
func (o *GetClosestPopsParams) WithURL(url *string) *GetClosestPopsParams {
	o.SetURL(url)
	return o
}

// SetURL adds the url to the get closest pops params
func (o *GetClosestPopsParams) SetURL(url *string) {
	o.URL = url
}

// WriteToRequest writes these params to a swagger request
func (o *GetClosestPopsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.URL != nil {

		// query param url
		var qrURL string

		if o.URL != nil {
			qrURL = *o.URL
		}
		qURL := qrURL
		if qURL != "" {

			if err := r.SetQueryParam("url", qURL); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
