// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/renderinc/stackpath-cdn-go/models"
)

// GetOriginsReader is a Reader for the GetOrigins structure.
type GetOriginsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOriginsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOriginsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetOriginsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetOriginsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetOriginsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetOriginsOK creates a GetOriginsOK with default headers values
func NewGetOriginsOK() *GetOriginsOK {
	return &GetOriginsOK{}
}

/* GetOriginsOK describes a response with status code 200, with default header values.

GetOriginsOK get origins o k
*/
type GetOriginsOK struct {
	Payload *models.CdnGetOriginsResponse
}

func (o *GetOriginsOK) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/origins][%d] getOriginsOK  %+v", 200, o.Payload)
}
func (o *GetOriginsOK) GetPayload() *models.CdnGetOriginsResponse {
	return o.Payload
}

func (o *GetOriginsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CdnGetOriginsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOriginsUnauthorized creates a GetOriginsUnauthorized with default headers values
func NewGetOriginsUnauthorized() *GetOriginsUnauthorized {
	return &GetOriginsUnauthorized{}
}

/* GetOriginsUnauthorized describes a response with status code 401, with default header values.

Returned when an unauthorized request is attempted.
*/
type GetOriginsUnauthorized struct {
	Payload *models.APIStatus
}

func (o *GetOriginsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/origins][%d] getOriginsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetOriginsUnauthorized) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *GetOriginsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOriginsInternalServerError creates a GetOriginsInternalServerError with default headers values
func NewGetOriginsInternalServerError() *GetOriginsInternalServerError {
	return &GetOriginsInternalServerError{}
}

/* GetOriginsInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetOriginsInternalServerError struct {
	Payload *models.APIStatus
}

func (o *GetOriginsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/origins][%d] getOriginsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetOriginsInternalServerError) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *GetOriginsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOriginsDefault creates a GetOriginsDefault with default headers values
func NewGetOriginsDefault(code int) *GetOriginsDefault {
	return &GetOriginsDefault{
		_statusCode: code,
	}
}

/* GetOriginsDefault describes a response with status code -1, with default header values.

Default error structure.
*/
type GetOriginsDefault struct {
	_statusCode int

	Payload *models.APIStatus
}

// Code gets the status code for the get origins default response
func (o *GetOriginsDefault) Code() int {
	return o._statusCode
}

func (o *GetOriginsDefault) Error() string {
	return fmt.Sprintf("[GET /cdn/v1/stacks/{stack_id}/origins][%d] GetOrigins default  %+v", o._statusCode, o.Payload)
}
func (o *GetOriginsDefault) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *GetOriginsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
