// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/renderinc/stackpath-cdn-go/models"
)

// UpdateSiteScriptReader is a Reader for the UpdateSiteScript structure.
type UpdateSiteScriptReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSiteScriptReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateSiteScriptOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateSiteScriptUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateSiteScriptInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewUpdateSiteScriptDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateSiteScriptOK creates a UpdateSiteScriptOK with default headers values
func NewUpdateSiteScriptOK() *UpdateSiteScriptOK {
	return &UpdateSiteScriptOK{}
}

/* UpdateSiteScriptOK describes a response with status code 200, with default header values.

UpdateSiteScriptOK update site script o k
*/
type UpdateSiteScriptOK struct {
	Payload *models.CdnUpdateSiteScriptResponse
}

func (o *UpdateSiteScriptOK) Error() string {
	return fmt.Sprintf("[PATCH /cdn/v1/stacks/{stack_id}/sites/{site_id}/scripts/{script_id}][%d] updateSiteScriptOK  %+v", 200, o.Payload)
}
func (o *UpdateSiteScriptOK) GetPayload() *models.CdnUpdateSiteScriptResponse {
	return o.Payload
}

func (o *UpdateSiteScriptOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CdnUpdateSiteScriptResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateSiteScriptUnauthorized creates a UpdateSiteScriptUnauthorized with default headers values
func NewUpdateSiteScriptUnauthorized() *UpdateSiteScriptUnauthorized {
	return &UpdateSiteScriptUnauthorized{}
}

/* UpdateSiteScriptUnauthorized describes a response with status code 401, with default header values.

Returned when an unauthorized request is attempted.
*/
type UpdateSiteScriptUnauthorized struct {
	Payload *models.APIStatus
}

func (o *UpdateSiteScriptUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /cdn/v1/stacks/{stack_id}/sites/{site_id}/scripts/{script_id}][%d] updateSiteScriptUnauthorized  %+v", 401, o.Payload)
}
func (o *UpdateSiteScriptUnauthorized) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *UpdateSiteScriptUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateSiteScriptInternalServerError creates a UpdateSiteScriptInternalServerError with default headers values
func NewUpdateSiteScriptInternalServerError() *UpdateSiteScriptInternalServerError {
	return &UpdateSiteScriptInternalServerError{}
}

/* UpdateSiteScriptInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type UpdateSiteScriptInternalServerError struct {
	Payload *models.APIStatus
}

func (o *UpdateSiteScriptInternalServerError) Error() string {
	return fmt.Sprintf("[PATCH /cdn/v1/stacks/{stack_id}/sites/{site_id}/scripts/{script_id}][%d] updateSiteScriptInternalServerError  %+v", 500, o.Payload)
}
func (o *UpdateSiteScriptInternalServerError) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *UpdateSiteScriptInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateSiteScriptDefault creates a UpdateSiteScriptDefault with default headers values
func NewUpdateSiteScriptDefault(code int) *UpdateSiteScriptDefault {
	return &UpdateSiteScriptDefault{
		_statusCode: code,
	}
}

/* UpdateSiteScriptDefault describes a response with status code -1, with default header values.

Default error structure.
*/
type UpdateSiteScriptDefault struct {
	_statusCode int

	Payload *models.APIStatus
}

// Code gets the status code for the update site script default response
func (o *UpdateSiteScriptDefault) Code() int {
	return o._statusCode
}

func (o *UpdateSiteScriptDefault) Error() string {
	return fmt.Sprintf("[PATCH /cdn/v1/stacks/{stack_id}/sites/{site_id}/scripts/{script_id}][%d] UpdateSiteScript default  %+v", o._statusCode, o.Payload)
}
func (o *UpdateSiteScriptDefault) GetPayload() *models.APIStatus {
	return o.Payload
}

func (o *UpdateSiteScriptDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
