// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// BandwidthRateLimitInitialBurstUnitsEnumWrapperValue bandwidth rate limit initial burst units enum wrapper value
//
// swagger:model BandwidthRateLimitInitialBurstUnitsEnumWrapperValue
type BandwidthRateLimitInitialBurstUnitsEnumWrapperValue string

const (

	// BandwidthRateLimitInitialBurstUnitsEnumWrapperValueUNKNOWN captures enum value "UNKNOWN"
	BandwidthRateLimitInitialBurstUnitsEnumWrapperValueUNKNOWN BandwidthRateLimitInitialBurstUnitsEnumWrapperValue = "UNKNOWN"

	// BandwidthRateLimitInitialBurstUnitsEnumWrapperValueByte captures enum value "byte"
	BandwidthRateLimitInitialBurstUnitsEnumWrapperValueByte BandwidthRateLimitInitialBurstUnitsEnumWrapperValue = "byte"

	// BandwidthRateLimitInitialBurstUnitsEnumWrapperValueKilobyte captures enum value "kilobyte"
	BandwidthRateLimitInitialBurstUnitsEnumWrapperValueKilobyte BandwidthRateLimitInitialBurstUnitsEnumWrapperValue = "kilobyte"
)

// for schema
var bandwidthRateLimitInitialBurstUnitsEnumWrapperValueEnum []interface{}

func init() {
	var res []BandwidthRateLimitInitialBurstUnitsEnumWrapperValue
	if err := json.Unmarshal([]byte(`["UNKNOWN","byte","kilobyte"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		bandwidthRateLimitInitialBurstUnitsEnumWrapperValueEnum = append(bandwidthRateLimitInitialBurstUnitsEnumWrapperValueEnum, v)
	}
}

func (m BandwidthRateLimitInitialBurstUnitsEnumWrapperValue) validateBandwidthRateLimitInitialBurstUnitsEnumWrapperValueEnum(path, location string, value BandwidthRateLimitInitialBurstUnitsEnumWrapperValue) error {
	if err := validate.EnumCase(path, location, value, bandwidthRateLimitInitialBurstUnitsEnumWrapperValueEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this bandwidth rate limit initial burst units enum wrapper value
func (m BandwidthRateLimitInitialBurstUnitsEnumWrapperValue) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateBandwidthRateLimitInitialBurstUnitsEnumWrapperValueEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this bandwidth rate limit initial burst units enum wrapper value based on context it is used
func (m BandwidthRateLimitInitialBurstUnitsEnumWrapperValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
