// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CdnGetCDNIpsResponse The response from a request to retrieve IP addresses used by the StackPath edge network
// swagger:model cdnGetCDNIPsResponse
type CdnGetCDNIpsResponse struct {

	// The requested IP addresses
	Results []string `json:"results,omitempty"`
}

// Validate validates this cdn get c d n ips response
func (m *CdnGetCDNIpsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CdnGetCDNIpsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CdnGetCDNIpsResponse) UnmarshalBinary(b []byte) error {
	var res CdnGetCDNIpsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
