// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CdnRequestCertificateRequest cdn request certificate request
// swagger:model cdnRequestCertificateRequest
type CdnRequestCertificateRequest struct {

	// hosts
	Hosts []string `json:"hosts"`
}

// Validate validates this cdn request certificate request
func (m *CdnRequestCertificateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CdnRequestCertificateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CdnRequestCertificateRequest) UnmarshalBinary(b []byte) error {
	var res CdnRequestCertificateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
