// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CdnVerificationRequirements cdn verification requirements
// swagger:model cdnVerificationRequirements
type CdnVerificationRequirements struct {

	// dns verification details
	DNSVerificationDetails *CdnDNSVerificationDetails `json:"dnsVerificationDetails,omitempty"`
}

// Validate validates this cdn verification requirements
func (m *CdnVerificationRequirements) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDNSVerificationDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CdnVerificationRequirements) validateDNSVerificationDetails(formats strfmt.Registry) error {

	if swag.IsZero(m.DNSVerificationDetails) { // not required
		return nil
	}

	if m.DNSVerificationDetails != nil {
		if err := m.DNSVerificationDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dnsVerificationDetails")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CdnVerificationRequirements) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CdnVerificationRequirements) UnmarshalBinary(b []byte) error {
	var res CdnVerificationRequirements
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
