// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CdnUpdateSiteCertificateHostsRequest A request to update an SSL certificate's hosts
// swagger:model cdnUpdateSiteCertificateHostsRequest
type CdnUpdateSiteCertificateHostsRequest struct {

	// The SSL certificated common and SAN hosts
	Hosts []string `json:"hosts"`
}

// Validate validates this cdn update site certificate hosts request
func (m *CdnUpdateSiteCertificateHostsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CdnUpdateSiteCertificateHostsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CdnUpdateSiteCertificateHostsRequest) UnmarshalBinary(b []byte) error {
	var res CdnUpdateSiteCertificateHostsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
