// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CdnCreateSiteRequestOrigin cdn create site request origin
// swagger:model cdnCreateSiteRequestOrigin
type CdnCreateSiteRequestOrigin struct {

	// hostname
	Hostname string `json:"hostname,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// port
	Port int32 `json:"port,omitempty"`

	// secure port
	SecurePort int32 `json:"securePort,omitempty"`
}

// Validate validates this cdn create site request origin
func (m *CdnCreateSiteRequestOrigin) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CdnCreateSiteRequestOrigin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CdnCreateSiteRequestOrigin) UnmarshalBinary(b []byte) error {
	var res CdnCreateSiteRequestOrigin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
