// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CdnPurgeContentResponse cdn purge content response
// swagger:model cdnPurgeContentResponse
type CdnPurgeContentResponse struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this cdn purge content response
func (m *CdnPurgeContentResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CdnPurgeContentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CdnPurgeContentResponse) UnmarshalBinary(b []byte) error {
	var res CdnPurgeContentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
