// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// CdnCreateSiteRequestFeature cdn create site request feature
// swagger:model cdnCreateSiteRequestFeature
type CdnCreateSiteRequestFeature string

const (

	// CdnCreateSiteRequestFeatureCDN captures enum value "CDN"
	CdnCreateSiteRequestFeatureCDN CdnCreateSiteRequestFeature = "CDN"

	// CdnCreateSiteRequestFeatureWAF captures enum value "WAF"
	CdnCreateSiteRequestFeatureWAF CdnCreateSiteRequestFeature = "WAF"
)

// for schema
var cdnCreateSiteRequestFeatureEnum []interface{}

func init() {
	var res []CdnCreateSiteRequestFeature
	if err := json.Unmarshal([]byte(`["CDN","WAF"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		cdnCreateSiteRequestFeatureEnum = append(cdnCreateSiteRequestFeatureEnum, v)
	}
}

func (m CdnCreateSiteRequestFeature) validateCdnCreateSiteRequestFeatureEnum(path, location string, value CdnCreateSiteRequestFeature) error {
	if err := validate.Enum(path, location, value, cdnCreateSiteRequestFeatureEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this cdn create site request feature
func (m CdnCreateSiteRequestFeature) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateCdnCreateSiteRequestFeatureEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
