// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CdncustconfOrigin cdncustconf origin
//
// swagger:model cdncustconfOrigin
type CdncustconfOrigin struct {

	// host
	Host string `json:"host,omitempty"`

	// This is used by the API to perform conflict checking
	ID string `json:"id,omitempty"`

	// String of values delimited by a ',' character.
	OriginCacheHeaders string `json:"originCacheHeaders,omitempty"`

	// String of values delimited by a '|' character.
	OriginPullHeaders string `json:"originPullHeaders,omitempty"`
}

// Validate validates this cdncustconf origin
func (m *CdncustconfOrigin) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cdncustconf origin based on context it is used
func (m *CdncustconfOrigin) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CdncustconfOrigin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CdncustconfOrigin) UnmarshalBinary(b []byte) error {
	var res CdncustconfOrigin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
