// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CustconfOriginPersistentConnections The origin persistent connection settings are used to enable persistent connections to origins
//
// swagger:model custconfOriginPersistentConnections
type CustconfOriginPersistentConnections struct {

	// enabled
	Enabled bool `json:"enabled"`

	// This is used by the API to perform conflict checking
	ID string `json:"id,omitempty"`
}

// Validate validates this custconf origin persistent connections
func (m *CustconfOriginPersistentConnections) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this custconf origin persistent connections based on context it is used
func (m *CustconfOriginPersistentConnections) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfOriginPersistentConnections) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfOriginPersistentConnections) UnmarshalBinary(b []byte) error {
	var res CustconfOriginPersistentConnections
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
