// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfRequestReceiptServer custconf request receipt server
// swagger:model custconfRequestReceiptServer
type CustconfRequestReceiptServer struct {

	// connection timeout
	ConnectionTimeout int64 `json:"connectionTimeout,omitempty"`

	// host
	Host string `json:"host,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// max batch size
	MaxBatchSize int64 `json:"maxBatchSize,omitempty"`
}

// Validate validates this custconf request receipt server
func (m *CustconfRequestReceiptServer) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfRequestReceiptServer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfRequestReceiptServer) UnmarshalBinary(b []byte) error {
	var res CustconfRequestReceiptServer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
