// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfAuthSignUrlsInPlaylist Automatically apply my URL Signing policy to URLs inside my HLS playlists.
// swagger:model custconfAuthSignUrlsInPlaylist
type CustconfAuthSignUrlsInPlaylist struct {

	// cookie name
	CookieName string `json:"cookieName,omitempty"`

	// enabled
	Enabled bool `json:"enabled"`

	// extend TTL
	ExtendTTL int64 `json:"extendTTL,omitempty"`

	// String of values deliminated by a ',' character.
	FilenamePatterns string `json:"filenamePatterns,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// use cookie
	UseCookie bool `json:"useCookie"`
}

// Validate validates this custconf auth sign urls in playlist
func (m *CustconfAuthSignUrlsInPlaylist) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfAuthSignUrlsInPlaylist) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfAuthSignUrlsInPlaylist) UnmarshalBinary(b []byte) error {
	var res CustconfAuthSignUrlsInPlaylist
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
