// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfFlvPseudoStreaming custconf flv pseudo streaming
// swagger:model custconfFlvPseudoStreaming
type CustconfFlvPseudoStreaming struct {

	// enabled
	Enabled bool `json:"enabled"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// initial byte size
	InitialByteSize string `json:"initialByteSize,omitempty"`

	// jump to byte initial bytes param
	JumpToByteInitialBytesParam string `json:"jumpToByteInitialBytesParam,omitempty"`

	// jump to byte start offset param
	JumpToByteStartOffsetParam string `json:"jumpToByteStartOffsetParam,omitempty"`
}

// Validate validates this custconf flv pseudo streaming
func (m *CustconfFlvPseudoStreaming) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfFlvPseudoStreaming) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfFlvPseudoStreaming) UnmarshalBinary(b []byte) error {
	var res CustconfFlvPseudoStreaming
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
