// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfHttp2Support Enable support of HTTP2
// swagger:model custconfHttp2Support
type CustconfHttp2Support struct {

	// Enable support of HTTP2
	Enabled bool `json:"enabled,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// String of values deliminated by a ',' character.
	PopFilter string `json:"popFilter,omitempty"`

	// String of values deliminated by a ',' character.
	RegionFilter string `json:"regionFilter,omitempty"`
}

// Validate validates this custconf http2 support
func (m *CustconfHttp2Support) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfHttp2Support) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfHttp2Support) UnmarshalBinary(b []byte) error {
	var res CustconfHttp2Support
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
