// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfInternalError The CDN internal error caching policy allows you to control the TTL for
// internally generated errors in the caching servers.
// swagger:model custconfInternalError
type CustconfInternalError struct {

	// enabled
	Enabled bool `json:"enabled"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// The default caching time for internally generated errors.
	MaxAge int32 `json:"maxAge,omitempty"`
}

// Validate validates this custconf internal error
func (m *CustconfInternalError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfInternalError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfInternalError) UnmarshalBinary(b []byte) error {
	var res CustconfInternalError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
