// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CustconfClientRequestModification custconf client request modification
// swagger:model custconfClientRequestModification
type CustconfClientRequestModification struct {

	// String of values deliminated by a '|' character. This is the static HTTP
	// header you want inserted into the CDN request. Start value with "append:"
	// or "replace:" which defines if Header will be replace or added. Default is
	// append.
	AddHeaders string `json:"addHeaders,omitempty"`

	// client request filter
	ClientRequestFilter []*CustconfRequestFilter `json:"clientRequestFilter"`

	// enabled
	Enabled bool `json:"enabled"`

	// flow control
	FlowControl CustconfClientRequestModificationFlowControlEnumWrapperValue `json:"flowControl,omitempty"`

	// String of values deliminated by a ',' character.
	HeaderFilter string `json:"headerFilter,omitempty"`

	// header pattern
	HeaderPattern string `json:"headerPattern,omitempty"`

	// header rewrite
	HeaderRewrite string `json:"headerRewrite,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// String of values deliminated by a ',' character.
	MethodFilter string `json:"methodFilter,omitempty"`

	// String of values deliminated by a ',' character.
	PathFilter string `json:"pathFilter,omitempty"`

	// url pattern
	URLPattern string `json:"urlPattern,omitempty"`

	// url rewrite
	URLRewrite string `json:"urlRewrite,omitempty"`
}

// Validate validates this custconf client request modification
func (m *CustconfClientRequestModification) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientRequestFilter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFlowControl(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CustconfClientRequestModification) validateClientRequestFilter(formats strfmt.Registry) error {

	if swag.IsZero(m.ClientRequestFilter) { // not required
		return nil
	}

	for i := 0; i < len(m.ClientRequestFilter); i++ {
		if swag.IsZero(m.ClientRequestFilter[i]) { // not required
			continue
		}

		if m.ClientRequestFilter[i] != nil {
			if err := m.ClientRequestFilter[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("clientRequestFilter" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CustconfClientRequestModification) validateFlowControl(formats strfmt.Registry) error {

	if swag.IsZero(m.FlowControl) { // not required
		return nil
	}

	if err := m.FlowControl.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("flowControl")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CustconfClientRequestModification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfClientRequestModification) UnmarshalBinary(b []byte) error {
	var res CustconfClientRequestModification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
