// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfRobotsTxt custconf robots txt
// swagger:model custconfRobotsTxt
type CustconfRobotsTxt struct {

	// cache control header
	CacheControlHeader string `json:"cacheControlHeader,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// file
	File string `json:"file,omitempty"`

	// String of values deliminated by a ',' character.
	HeaderFilter string `json:"headerFilter,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// String of values deliminated by a ',' character.
	MethodFilter string `json:"methodFilter,omitempty"`

	// String of values deliminated by a ',' character.
	PathFilter string `json:"pathFilter,omitempty"`
}

// Validate validates this custconf robots txt
func (m *CustconfRobotsTxt) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfRobotsTxt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfRobotsTxt) UnmarshalBinary(b []byte) error {
	var res CustconfRobotsTxt
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
