// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfDrainTCPSendBuffer Instructs the CDN caching server to block until the socket send buffer is
// drained below a threshold after serving a request.
// swagger:model custconfDrainTCPSendBuffer
type CustconfDrainTCPSendBuffer struct {

	// Force edges to wait for acknowledge of data in the TCP send buffer after
	// writing the requested content into the socket.
	Enabled bool `json:"enabled"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`
}

// Validate validates this custconf drain TCP send buffer
func (m *CustconfDrainTCPSendBuffer) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfDrainTCPSendBuffer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfDrainTCPSendBuffer) UnmarshalBinary(b []byte) error {
	var res CustconfDrainTCPSendBuffer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
