// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfWafClustersOverride custconf waf clusters override
// swagger:model custconfWafClustersOverride
type CustconfWafClustersOverride struct {

	// enabled
	Enabled bool `json:"enabled"`

	// String of values deliminated by a ',' character.
	HeaderFilter string `json:"headerFilter,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// String of values deliminated by a ',' character.
	MethodFilter string `json:"methodFilter,omitempty"`

	// String of values deliminated by a ',' character.
	PathFilter string `json:"pathFilter,omitempty"`

	// String of values deliminated by a ',' character.
	PopFilter string `json:"popFilter,omitempty"`

	// String of values deliminated by a ',' character.
	ServerList string `json:"serverList,omitempty"`
}

// Validate validates this custconf waf clusters override
func (m *CustconfWafClustersOverride) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfWafClustersOverride) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfWafClustersOverride) UnmarshalBinary(b []byte) error {
	var res CustconfWafClustersOverride
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
