// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfClientKeepAlive The clientKeepAlive policy allows you to specify how long you want the CDN
// caching server to keep an client connection open after serving a request.
// swagger:model custconfClientKeepAlive
type CustconfClientKeepAlive struct {

	// enabled
	Enabled bool `json:"enabled"`

	// String of values deliminated by a ',' character.
	HeaderFilter string `json:"headerFilter,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// String of values deliminated by a ',' character.
	MethodFilter string `json:"methodFilter,omitempty"`

	// String of values deliminated by a ',' character.
	PathFilter string `json:"pathFilter,omitempty"`

	// String of values deliminated by a ',' character.
	PopFilter string `json:"popFilter,omitempty"`

	// String of values deliminated by a ',' character.
	RegionFilter string `json:"regionFilter,omitempty"`

	// Timeout in seconds for idle client connections of GFS.
	Timeout int32 `json:"timeout,omitempty"`
}

// Validate validates this custconf client keep alive
func (m *CustconfClientKeepAlive) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfClientKeepAlive) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfClientKeepAlive) UnmarshalBinary(b []byte) error {
	var res CustconfClientKeepAlive
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
