// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfXForwardedForBehavior custconf x forwarded for behavior
// swagger:model custconfXForwardedForBehavior
type CustconfXForwardedForBehavior struct {

	// enabled
	Enabled bool `json:"enabled"`

	// follow Http spec
	FollowHTTPSpec bool `json:"followHttpSpec"`

	// String of values deliminated by a ',' character.
	HeaderFilter string `json:"headerFilter,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// String of values deliminated by a ',' character.
	MethodFilter string `json:"methodFilter,omitempty"`

	// String of values deliminated by a ',' character.
	PathFilter string `json:"pathFilter,omitempty"`
}

// Validate validates this custconf x forwarded for behavior
func (m *CustconfXForwardedForBehavior) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfXForwardedForBehavior) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfXForwardedForBehavior) UnmarshalBinary(b []byte) error {
	var res CustconfXForwardedForBehavior
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
