// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfRequestReceiptReportPercentage The delivery receipts report percentage policy allows you to configure the
// percentage of requests to provide delivery confirmation receipts.
// swagger:model custconfRequestReceiptReportPercentage
type CustconfRequestReceiptReportPercentage struct {

	// cache hit report percentage
	CacheHitReportPercentage int32 `json:"cacheHitReportPercentage,omitempty"`

	// dedup report percentage
	DedupReportPercentage int32 `json:"dedupReportPercentage,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// origin pull report percentage
	OriginPullReportPercentage int32 `json:"originPullReportPercentage,omitempty"`
}

// Validate validates this custconf request receipt report percentage
func (m *CustconfRequestReceiptReportPercentage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfRequestReceiptReportPercentage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfRequestReceiptReportPercentage) UnmarshalBinary(b []byte) error {
	var res CustconfRequestReceiptReportPercentage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
