// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// CustconfClientRequestModificationFlowControlEnumWrapperValue custconf client request modification flow control enum wrapper value
//
// swagger:model custconfClientRequestModificationFlowControlEnumWrapperValue
type CustconfClientRequestModificationFlowControlEnumWrapperValue string

const (

	// CustconfClientRequestModificationFlowControlEnumWrapperValueUNKNOWN captures enum value "UNKNOWN"
	CustconfClientRequestModificationFlowControlEnumWrapperValueUNKNOWN CustconfClientRequestModificationFlowControlEnumWrapperValue = "UNKNOWN"

	// CustconfClientRequestModificationFlowControlEnumWrapperValueNext captures enum value "next"
	CustconfClientRequestModificationFlowControlEnumWrapperValueNext CustconfClientRequestModificationFlowControlEnumWrapperValue = "next"

	// CustconfClientRequestModificationFlowControlEnumWrapperValueBreak captures enum value "break"
	CustconfClientRequestModificationFlowControlEnumWrapperValueBreak CustconfClientRequestModificationFlowControlEnumWrapperValue = "break"
)

// for schema
var custconfClientRequestModificationFlowControlEnumWrapperValueEnum []interface{}

func init() {
	var res []CustconfClientRequestModificationFlowControlEnumWrapperValue
	if err := json.Unmarshal([]byte(`["UNKNOWN","next","break"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		custconfClientRequestModificationFlowControlEnumWrapperValueEnum = append(custconfClientRequestModificationFlowControlEnumWrapperValueEnum, v)
	}
}

func (m CustconfClientRequestModificationFlowControlEnumWrapperValue) validateCustconfClientRequestModificationFlowControlEnumWrapperValueEnum(path, location string, value CustconfClientRequestModificationFlowControlEnumWrapperValue) error {
	if err := validate.EnumCase(path, location, value, custconfClientRequestModificationFlowControlEnumWrapperValueEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this custconf client request modification flow control enum wrapper value
func (m CustconfClientRequestModificationFlowControlEnumWrapperValue) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateCustconfClientRequestModificationFlowControlEnumWrapperValueEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this custconf client request modification flow control enum wrapper value based on context it is used
func (m CustconfClientRequestModificationFlowControlEnumWrapperValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
