// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// CustconfMidTierCachingProtocolEnumWrapperValue custconf mid tier caching protocol enum wrapper value
//
// swagger:model custconfMidTierCachingProtocolEnumWrapperValue
type CustconfMidTierCachingProtocolEnumWrapperValue string

const (

	// CustconfMidTierCachingProtocolEnumWrapperValueUNKNOWN captures enum value "UNKNOWN"
	CustconfMidTierCachingProtocolEnumWrapperValueUNKNOWN CustconfMidTierCachingProtocolEnumWrapperValue = "UNKNOWN"

	// CustconfMidTierCachingProtocolEnumWrapperValueHTTP captures enum value "http"
	CustconfMidTierCachingProtocolEnumWrapperValueHTTP CustconfMidTierCachingProtocolEnumWrapperValue = "http"

	// CustconfMidTierCachingProtocolEnumWrapperValueHTTPS captures enum value "https"
	CustconfMidTierCachingProtocolEnumWrapperValueHTTPS CustconfMidTierCachingProtocolEnumWrapperValue = "https"

	// CustconfMidTierCachingProtocolEnumWrapperValueMatch captures enum value "match"
	CustconfMidTierCachingProtocolEnumWrapperValueMatch CustconfMidTierCachingProtocolEnumWrapperValue = "match"
)

// for schema
var custconfMidTierCachingProtocolEnumWrapperValueEnum []interface{}

func init() {
	var res []CustconfMidTierCachingProtocolEnumWrapperValue
	if err := json.Unmarshal([]byte(`["UNKNOWN","http","https","match"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		custconfMidTierCachingProtocolEnumWrapperValueEnum = append(custconfMidTierCachingProtocolEnumWrapperValueEnum, v)
	}
}

func (m CustconfMidTierCachingProtocolEnumWrapperValue) validateCustconfMidTierCachingProtocolEnumWrapperValueEnum(path, location string, value CustconfMidTierCachingProtocolEnumWrapperValue) error {
	if err := validate.EnumCase(path, location, value, custconfMidTierCachingProtocolEnumWrapperValueEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this custconf mid tier caching protocol enum wrapper value
func (m CustconfMidTierCachingProtocolEnumWrapperValue) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateCustconfMidTierCachingProtocolEnumWrapperValueEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this custconf mid tier caching protocol enum wrapper value based on context it is used
func (m CustconfMidTierCachingProtocolEnumWrapperValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
