// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfAccessLogger Global settings that AccessLogger uses when storing access logs, origin pull
// logs and receipt logs
// swagger:model custconfAccessLogger
type CustconfAccessLogger struct {

	// enable compression
	EnableCompression bool `json:"enableCompression,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// expire time h c s
	ExpireTimeHCS int64 `json:"expireTimeHCS,omitempty"`

	// expire time local
	ExpireTimeLocal int64 `json:"expireTimeLocal,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// upload to h c s
	UploadToHCS bool `json:"uploadToHCS,omitempty"`
}

// Validate validates this custconf access logger
func (m *CustconfAccessLogger) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfAccessLogger) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfAccessLogger) UnmarshalBinary(b []byte) error {
	var res CustconfAccessLogger
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
