// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfTossbackAlways Instructs the CDN caching server to always toss a connection back to Doppler
// to choose the edge for next pipeline request.
// swagger:model custconfTossbackAlways
type CustconfTossbackAlways struct {

	// Force the tossback of connections from the caching server to Doppler.
	Enabled bool `json:"enabled,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`
}

// Validate validates this custconf tossback always
func (m *CustconfTossbackAlways) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfTossbackAlways) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfTossbackAlways) UnmarshalBinary(b []byte) error {
	var res CustconfTossbackAlways
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
