// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CustconfCacheKeyModification The Cache Key Modification policy allows for manipulation of the way the
// cache uniquely stores assets.
// swagger:model custconfCacheKeyModification
type CustconfCacheKeyModification struct {

	// enabled
	Enabled bool `json:"enabled"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`

	// When set, purges and requests for a file will be case insensitive. This
	// setting is useful if you have a case insensitive origin server and would
	// like to avoid duplicating assets.
	NormalizeKeyPathToLowerCase bool `json:"normalizeKeyPathToLowerCase"`
}

// Validate validates this custconf cache key modification
func (m *CustconfCacheKeyModification) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustconfCacheKeyModification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfCacheKeyModification) UnmarshalBinary(b []byte) error {
	var res CustconfCacheKeyModification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
