// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValue custconf auth Url asymmetric sign tlu algorithm Id map enum wrapper value
//
// swagger:model custconfAuthUrlAsymmetricSignTluAlgorithmIdMapEnumWrapperValue
type CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValue string

const (

	// CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValueUNKNOWN captures enum value "UNKNOWN"
	CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValueUNKNOWN CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValue = "UNKNOWN"

	// CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValueHmacsha1 captures enum value "hmacsha1"
	CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValueHmacsha1 CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValue = "hmacsha1"

	// CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValueHmacsha256 captures enum value "hmacsha256"
	CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValueHmacsha256 CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValue = "hmacsha256"
)

// for schema
var custconfAuthUrlAsymmetricSignTluAlgorithmIdMapEnumWrapperValueEnum []interface{}

func init() {
	var res []CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValue
	if err := json.Unmarshal([]byte(`["UNKNOWN","hmacsha1","hmacsha256"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		custconfAuthUrlAsymmetricSignTluAlgorithmIdMapEnumWrapperValueEnum = append(custconfAuthUrlAsymmetricSignTluAlgorithmIdMapEnumWrapperValueEnum, v)
	}
}

func (m CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValue) validateCustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValueEnum(path, location string, value CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValue) error {
	if err := validate.EnumCase(path, location, value, custconfAuthUrlAsymmetricSignTluAlgorithmIdMapEnumWrapperValueEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this custconf auth Url asymmetric sign tlu algorithm Id map enum wrapper value
func (m CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValue) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateCustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValueEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this custconf auth Url asymmetric sign tlu algorithm Id map enum wrapper value based on context it is used
func (m CustconfAuthURLAsymmetricSignTluAlgorithmIDMapEnumWrapperValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
