// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CustconfBillableRegions List of delivery regions enabled for the platform.
// swagger:model custconfBillableRegions
type CustconfBillableRegions struct {

	// enabled regions
	EnabledRegions BillableRegionsEnabledRegionsEnumWrapperValue `json:"enabledRegions,omitempty"`

	// This is used by the API to perform conflict checking.
	ID string `json:"id,omitempty"`
}

// Validate validates this custconf billable regions
func (m *CustconfBillableRegions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnabledRegions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CustconfBillableRegions) validateEnabledRegions(formats strfmt.Registry) error {

	if swag.IsZero(m.EnabledRegions) { // not required
		return nil
	}

	if err := m.EnabledRegions.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("enabledRegions")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CustconfBillableRegions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustconfBillableRegions) UnmarshalBinary(b []byte) error {
	var res CustconfBillableRegions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
