// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// FileSegmentationInitialOriginRequestBehaviorEnumWrapperValue file segmentation initial origin request behavior enum wrapper value
// swagger:model FileSegmentationInitialOriginRequestBehaviorEnumWrapperValue
type FileSegmentationInitialOriginRequestBehaviorEnumWrapperValue string

const (

	// FileSegmentationInitialOriginRequestBehaviorEnumWrapperValueUNKNOWN captures enum value "UNKNOWN"
	FileSegmentationInitialOriginRequestBehaviorEnumWrapperValueUNKNOWN FileSegmentationInitialOriginRequestBehaviorEnumWrapperValue = "UNKNOWN"

	// FileSegmentationInitialOriginRequestBehaviorEnumWrapperValueRange captures enum value "range"
	FileSegmentationInitialOriginRequestBehaviorEnumWrapperValueRange FileSegmentationInitialOriginRequestBehaviorEnumWrapperValue = "range"

	// FileSegmentationInitialOriginRequestBehaviorEnumWrapperValueFull captures enum value "full"
	FileSegmentationInitialOriginRequestBehaviorEnumWrapperValueFull FileSegmentationInitialOriginRequestBehaviorEnumWrapperValue = "full"
)

// for schema
var fileSegmentationInitialOriginRequestBehaviorEnumWrapperValueEnum []interface{}

func init() {
	var res []FileSegmentationInitialOriginRequestBehaviorEnumWrapperValue
	if err := json.Unmarshal([]byte(`["UNKNOWN","range","full"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		fileSegmentationInitialOriginRequestBehaviorEnumWrapperValueEnum = append(fileSegmentationInitialOriginRequestBehaviorEnumWrapperValueEnum, v)
	}
}

func (m FileSegmentationInitialOriginRequestBehaviorEnumWrapperValue) validateFileSegmentationInitialOriginRequestBehaviorEnumWrapperValueEnum(path, location string, value FileSegmentationInitialOriginRequestBehaviorEnumWrapperValue) error {
	if err := validate.Enum(path, location, value, fileSegmentationInitialOriginRequestBehaviorEnumWrapperValueEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this file segmentation initial origin request behavior enum wrapper value
func (m FileSegmentationInitialOriginRequestBehaviorEnumWrapperValue) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateFileSegmentationInitialOriginRequestBehaviorEnumWrapperValueEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
