// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetMetricsResponseMetricSeries A series of analytics data suitable for a graph
// swagger:model GetMetricsResponseMetricSeries
type GetMetricsResponseMetricSeries struct {

	// A graphable key for the type of data in the analytics set
	Key string `json:"key,omitempty"`

	// Descriptions of the CDN metrics' samples
	Metrics []string `json:"metrics"`

	// The CDN metrics' data points
	Samples []*GetMetricsResponseMetricSample `json:"samples"`

	// The type of data in the analytics set
	Type string `json:"type,omitempty"`
}

// Validate validates this get metrics response metric series
func (m *GetMetricsResponseMetricSeries) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSamples(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetMetricsResponseMetricSeries) validateSamples(formats strfmt.Registry) error {

	if swag.IsZero(m.Samples) { // not required
		return nil
	}

	for i := 0; i < len(m.Samples); i++ {
		if swag.IsZero(m.Samples[i]) { // not required
			continue
		}

		if m.Samples[i] != nil {
			if err := m.Samples[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("samples" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetMetricsResponseMetricSeries) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetMetricsResponseMetricSeries) UnmarshalBinary(b []byte) error {
	var res GetMetricsResponseMetricSeries
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
