// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// OriginPullShieldBehaviorEnumWrapperValue origin pull shield behavior enum wrapper value
//
// swagger:model OriginPullShieldBehaviorEnumWrapperValue
type OriginPullShieldBehaviorEnumWrapperValue string

const (

	// OriginPullShieldBehaviorEnumWrapperValueUNKNOWN captures enum value "UNKNOWN"
	OriginPullShieldBehaviorEnumWrapperValueUNKNOWN OriginPullShieldBehaviorEnumWrapperValue = "UNKNOWN"

	// OriginPullShieldBehaviorEnumWrapperValueRedirect captures enum value "redirect"
	OriginPullShieldBehaviorEnumWrapperValueRedirect OriginPullShieldBehaviorEnumWrapperValue = "redirect"

	// OriginPullShieldBehaviorEnumWrapperValueTlb captures enum value "tlb"
	OriginPullShieldBehaviorEnumWrapperValueTlb OriginPullShieldBehaviorEnumWrapperValue = "tlb"
)

// for schema
var originPullShieldBehaviorEnumWrapperValueEnum []interface{}

func init() {
	var res []OriginPullShieldBehaviorEnumWrapperValue
	if err := json.Unmarshal([]byte(`["UNKNOWN","redirect","tlb"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		originPullShieldBehaviorEnumWrapperValueEnum = append(originPullShieldBehaviorEnumWrapperValueEnum, v)
	}
}

func (m OriginPullShieldBehaviorEnumWrapperValue) validateOriginPullShieldBehaviorEnumWrapperValueEnum(path, location string, value OriginPullShieldBehaviorEnumWrapperValue) error {
	if err := validate.EnumCase(path, location, value, originPullShieldBehaviorEnumWrapperValueEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this origin pull shield behavior enum wrapper value
func (m OriginPullShieldBehaviorEnumWrapperValue) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateOriginPullShieldBehaviorEnumWrapperValueEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this origin pull shield behavior enum wrapper value based on context it is used
func (m OriginPullShieldBehaviorEnumWrapperValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
