// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SchemacdnOrigin A CDN site's origin
//
// Origins are the original sources of the data that is cached by the CDN on request.
// swagger:model schemacdnOrigin
type SchemacdnOrigin struct {

	// Whether or not an origin is dedicated to a CDN site
	//
	// Dedicated origins cannot be used by any site other than that to which it is dedicated.
	Dedicated bool `json:"dedicated"`

	// An origin's hostname or IP address
	Hostname string `json:"hostname,omitempty"`

	// An origin's unique identifier
	ID string `json:"id,omitempty"`

	// An origin's path
	//
	// Paths default to "/"
	Path string `json:"path,omitempty"`

	// The HTTP port to connect to the origin
	Port int32 `json:"port,omitempty"`

	// The HTTPS port to connect to the origin
	SecurePort int32 `json:"securePort,omitempty"`

	// The ID of the CDN site to which an origin is dedicated
	SiteID string `json:"siteId,omitempty"`
}

// Validate validates this schemacdn origin
func (m *SchemacdnOrigin) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SchemacdnOrigin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SchemacdnOrigin) UnmarshalBinary(b []byte) error {
	var res SchemacdnOrigin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
