// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TypeEnum type enum
// swagger:model TypeEnum
type TypeEnum string

const (

	// TypeEnumCDN captures enum value "CDN"
	TypeEnumCDN TypeEnum = "CDN"

	// TypeEnumWAF captures enum value "WAF"
	TypeEnumWAF TypeEnum = "WAF"

	// TypeEnumAPI captures enum value "API"
	TypeEnumAPI TypeEnum = "API"
)

// for schema
var typeEnumEnum []interface{}

func init() {
	var res []TypeEnum
	if err := json.Unmarshal([]byte(`["CDN","WAF","API"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		typeEnumEnum = append(typeEnumEnum, v)
	}
}

func (m TypeEnum) validateTypeEnumEnum(path, location string, value TypeEnum) error {
	if err := validate.Enum(path, location, value, typeEnumEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this type enum
func (m TypeEnum) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTypeEnumEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
